version: 2
updates:
  - package-ecosystem: "composer"
    # Files stored in repository root
    directory: "/server/laravel"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: "chore: "
